// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace DogDaycareTracker.CUI.Tests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// AssertDogWasAdded - Use 'AssertDogWasAddedExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertDogWasAdded()
        {
            #region Variable Declarations
            HtmlDiv uIDogwasAddedPane5 = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIDogwasAddedPane5;
            #endregion

            // Wait for 2 seconds for user delay between actions; Verify that the 'InnerText' property of 'Dog was Added!' pane equals 'Dog was Added! '
            Playback.Wait(2000);
            Assert.AreEqual(this.AssertDogWasAddedExpectedValues.UIDogwasAddedPane5InnerText, uIDogwasAddedPane5.InnerText, "No! Dog was not added");
        }
        
        /// <summary>
        /// AssertMethod1 - Use 'AssertMethod1ExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod1()
        {
            #region Variable Declarations
            HtmlDiv uIDogwasAddedPane5 = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIDogwasAddedPane5;
            #endregion

            // Wait for 1 seconds for user delay between actions; Verify that the 'InnerText' property of 'Dog was Added!' pane equals 'Dog was Added! '
            Playback.Wait(1000);
            Assert.AreEqual(this.AssertMethod1ExpectedValues.UIDogwasAddedPane5InnerText, uIDogwasAddedPane5.InnerText, "fix");
        }
        
        /// <summary>
        /// AssertTheDogWasAdded - Use 'AssertTheDogWasAddedExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertTheDogWasAdded()
        {
            #region Variable Declarations
            HtmlDiv uIDogwasAddedPane5 = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIDogwasAddedPane5;
            #endregion

            // Wait for 2 seconds for user delay between actions; Verify that the 'InnerText' property of 'Dog was Added!' pane equals 'Dog was Added! '
            Playback.Wait(2000);
            Assert.AreEqual(this.AssertTheDogWasAddedExpectedValues.UIDogwasAddedPane5InnerText, uIDogwasAddedPane5.InnerText, "why wasn\'t added?");
        }
        
        /// <summary>
        /// Clickadddog - Test Case 79
        /// </summary>
        public void Clickadddog()
        {
            #region Variable Declarations
            HtmlInputButton uIAddDogButton = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIAddDogButton;
            #endregion

            // Click 'Add Dog' button
            Mouse.Click(uIAddDogButton, new Point(63, 23));
        }
        
        /// <summary>
        /// ClickAddNewDog - Test Case 42
        /// </summary>
        public void ClickAddNewDog()
        {
            #region Variable Declarations
            HtmlInputButton uIAddDogButton = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIAddDogButton;
            #endregion

            // Click 'Add Dog' button
            Mouse.Click(uIAddDogButton, new Point(74, 18));
        }
        
        /// <summary>
        /// DogNamedogname - Test Case 79 - Use 'DogNamedognameParams' to pass parameters into this method.
        /// </summary>
        public void DogNamedogname()
        {
            #region Variable Declarations
            HtmlEdit uIDogNameEdit = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIDogNameEdit;
            #endregion

            // Type 'Hootch' in 'DogName' text box
            uIDogNameEdit.Text = this.DogNamedognameParams.UIDogNameEditText;
        }
        
        /// <summary>
        /// DogWasAdded - Use 'DogWasAddedExpectedValues' to pass parameters into this method.
        /// </summary>
        public void DogWasAdded()
        {
            #region Variable Declarations
            HtmlDiv uIDogwasAddedPane5 = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIDogwasAddedPane5;
            #endregion

            // Wait for 1 seconds for user delay between actions; Verify that the 'InnerText' property of 'Dog was Added!' pane equals 'Dog was Added! '
            Playback.Wait(1000);
            Assert.AreEqual(this.DogWasAddedExpectedValues.UIDogwasAddedPane5InnerText, uIDogwasAddedPane5.InnerText, "fix");
        }
        
        /// <summary>
        /// Enterageage - Test Case 79 - Use 'EnterageageParams' to pass parameters into this method.
        /// </summary>
        public void Enterageage()
        {
            #region Variable Declarations
            HtmlEdit uIDogAgeEdit = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIDogAgeEdit;
            #endregion

            // Type '4' in 'DogAge' text box
            uIDogAgeEdit.Text = this.EnterageageParams.UIDogAgeEditText;
        }
        
        /// <summary>
        /// EnterDogAgedogage - Test Case 42 - Use 'EnterDogAgedogageParams' to pass parameters into this method.
        /// </summary>
        public void EnterDogAgedogage()
        {
            #region Variable Declarations
            HtmlEdit uIDogAgeEdit = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIDogAgeEdit;
            #endregion

            // Type '3' in 'DogAge' text box
            uIDogAgeEdit.Text = this.EnterDogAgedogageParams.UIDogAgeEditText;
        }
        
        /// <summary>
        /// EnterDogNamedogname - Test Case 42 - Use 'EnterDogNamedognameParams' to pass parameters into this method.
        /// </summary>
        public void EnterDogNamedogname()
        {
            #region Variable Declarations
            HtmlEdit uIDogNameEdit = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIDogNameEdit;
            #endregion

            // Type 'Hootch' in 'DogName' text box
            uIDogNameEdit.Text = this.EnterDogNamedognameParams.UIDogNameEditText;
        }
        
        /// <summary>
        /// EnterDogWeightdogweight - Test Case 42 - Use 'EnterDogWeightdogweightParams' to pass parameters into this method.
        /// </summary>
        public void EnterDogWeightdogweight()
        {
            #region Variable Declarations
            HtmlEdit uIDogWeightEdit = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIDogWeightEdit;
            #endregion

            // Type '11' in 'DogWeight' text box
            uIDogWeightEdit.Text = this.EnterDogWeightdogweightParams.UIDogWeightEditText;
        }
        
        /// <summary>
        /// Enterweightweight - Test Case 79 - Use 'EnterweightweightParams' to pass parameters into this method.
        /// </summary>
        public void Enterweightweight()
        {
            #region Variable Declarations
            HtmlEdit uIDogWeightEdit = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIDogWeightEdit;
            #endregion

            // Type '11' in 'DogWeight' text box
            uIDogWeightEdit.Text = this.EnterweightweightParams.UIDogWeightEditText;
        }
        
        /// <summary>
        /// NavigatetoAddnewdog - Test Case 42 - Use 'NavigatetoAddnewdogParams' to pass parameters into this method.
        /// </summary>
        public void NavigatetoAddnewdog()
        {

            // Go to web page 'http://drookddc.azurewebsites.net/' using new browser instance
            this.UINewtabInternetExplorWindow.LaunchUrl(new System.Uri(this.NavigatetoAddnewdogParams.UINewtabInternetExplorWindowUrl));
        }
        
        /// <summary>
        /// Navigatetopage - Test Case 79 - Use 'NavigatetopageParams' to pass parameters into this method.
        /// </summary>
        public void Navigatetopage()
        {

            // Go to web page 'http://drookddc.azurewebsites.net/' using new browser instance
            this.UINewtabInternetExplorWindow.LaunchUrl(new System.Uri(this.NavigatetopageParams.UINewtabInternetExplorWindowUrl));
        }
        
        #region Properties
        public virtual AssertDogWasAddedExpectedValues AssertDogWasAddedExpectedValues
        {
            get
            {
                if ((this.mAssertDogWasAddedExpectedValues == null))
                {
                    this.mAssertDogWasAddedExpectedValues = new AssertDogWasAddedExpectedValues();
                }
                return this.mAssertDogWasAddedExpectedValues;
            }
        }
        
        public virtual AssertMethod1ExpectedValues AssertMethod1ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod1ExpectedValues == null))
                {
                    this.mAssertMethod1ExpectedValues = new AssertMethod1ExpectedValues();
                }
                return this.mAssertMethod1ExpectedValues;
            }
        }
        
        public virtual AssertTheDogWasAddedExpectedValues AssertTheDogWasAddedExpectedValues
        {
            get
            {
                if ((this.mAssertTheDogWasAddedExpectedValues == null))
                {
                    this.mAssertTheDogWasAddedExpectedValues = new AssertTheDogWasAddedExpectedValues();
                }
                return this.mAssertTheDogWasAddedExpectedValues;
            }
        }
        
        public virtual DogNamedognameParams DogNamedognameParams
        {
            get
            {
                if ((this.mDogNamedognameParams == null))
                {
                    this.mDogNamedognameParams = new DogNamedognameParams();
                }
                return this.mDogNamedognameParams;
            }
        }
        
        public virtual DogWasAddedExpectedValues DogWasAddedExpectedValues
        {
            get
            {
                if ((this.mDogWasAddedExpectedValues == null))
                {
                    this.mDogWasAddedExpectedValues = new DogWasAddedExpectedValues();
                }
                return this.mDogWasAddedExpectedValues;
            }
        }
        
        public virtual EnterageageParams EnterageageParams
        {
            get
            {
                if ((this.mEnterageageParams == null))
                {
                    this.mEnterageageParams = new EnterageageParams();
                }
                return this.mEnterageageParams;
            }
        }
        
        public virtual EnterDogAgedogageParams EnterDogAgedogageParams
        {
            get
            {
                if ((this.mEnterDogAgedogageParams == null))
                {
                    this.mEnterDogAgedogageParams = new EnterDogAgedogageParams();
                }
                return this.mEnterDogAgedogageParams;
            }
        }
        
        public virtual EnterDogNamedognameParams EnterDogNamedognameParams
        {
            get
            {
                if ((this.mEnterDogNamedognameParams == null))
                {
                    this.mEnterDogNamedognameParams = new EnterDogNamedognameParams();
                }
                return this.mEnterDogNamedognameParams;
            }
        }
        
        public virtual EnterDogWeightdogweightParams EnterDogWeightdogweightParams
        {
            get
            {
                if ((this.mEnterDogWeightdogweightParams == null))
                {
                    this.mEnterDogWeightdogweightParams = new EnterDogWeightdogweightParams();
                }
                return this.mEnterDogWeightdogweightParams;
            }
        }
        
        public virtual EnterweightweightParams EnterweightweightParams
        {
            get
            {
                if ((this.mEnterweightweightParams == null))
                {
                    this.mEnterweightweightParams = new EnterweightweightParams();
                }
                return this.mEnterweightweightParams;
            }
        }
        
        public virtual NavigatetoAddnewdogParams NavigatetoAddnewdogParams
        {
            get
            {
                if ((this.mNavigatetoAddnewdogParams == null))
                {
                    this.mNavigatetoAddnewdogParams = new NavigatetoAddnewdogParams();
                }
                return this.mNavigatetoAddnewdogParams;
            }
        }
        
        public virtual NavigatetopageParams NavigatetopageParams
        {
            get
            {
                if ((this.mNavigatetopageParams == null))
                {
                    this.mNavigatetopageParams = new NavigatetopageParams();
                }
                return this.mNavigatetopageParams;
            }
        }
        
        public UINewtabInternetExplorWindow UINewtabInternetExplorWindow
        {
            get
            {
                if ((this.mUINewtabInternetExplorWindow == null))
                {
                    this.mUINewtabInternetExplorWindow = new UINewtabInternetExplorWindow();
                }
                return this.mUINewtabInternetExplorWindow;
            }
        }
        #endregion
        
        #region Fields
        private AssertDogWasAddedExpectedValues mAssertDogWasAddedExpectedValues;
        
        private AssertMethod1ExpectedValues mAssertMethod1ExpectedValues;
        
        private AssertTheDogWasAddedExpectedValues mAssertTheDogWasAddedExpectedValues;
        
        private DogNamedognameParams mDogNamedognameParams;
        
        private DogWasAddedExpectedValues mDogWasAddedExpectedValues;
        
        private EnterageageParams mEnterageageParams;
        
        private EnterDogAgedogageParams mEnterDogAgedogageParams;
        
        private EnterDogNamedognameParams mEnterDogNamedognameParams;
        
        private EnterDogWeightdogweightParams mEnterDogWeightdogweightParams;
        
        private EnterweightweightParams mEnterweightweightParams;
        
        private NavigatetoAddnewdogParams mNavigatetoAddnewdogParams;
        
        private NavigatetopageParams mNavigatetopageParams;
        
        private UINewtabInternetExplorWindow mUINewtabInternetExplorWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertDogWasAdded'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class AssertDogWasAddedExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Wait for 2 seconds for user delay between actions; Verify that the 'InnerText' property of 'Dog was Added!' pane equals 'Dog was Added! '
        /// </summary>
        public string UIDogwasAddedPane5InnerText = "Dog was Added! ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class AssertMethod1ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Wait for 1 seconds for user delay between actions; Verify that the 'InnerText' property of 'Dog was Added!' pane equals 'Dog was Added! '
        /// </summary>
        public string UIDogwasAddedPane5InnerText = "Dog was Added! ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertTheDogWasAdded'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class AssertTheDogWasAddedExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Wait for 2 seconds for user delay between actions; Verify that the 'InnerText' property of 'Dog was Added!' pane equals 'Dog was Added! '
        /// </summary>
        public string UIDogwasAddedPane5InnerText = "Dog was Added! ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'DogNamedogname'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class DogNamedognameParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Hootch' in 'DogName' text box
        /// </summary>
        public string UIDogNameEditText = "Hootch";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'DogWasAdded'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class DogWasAddedExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Wait for 1 seconds for user delay between actions; Verify that the 'InnerText' property of 'Dog was Added!' pane equals 'Dog was Added! '
        /// </summary>
        public string UIDogwasAddedPane5InnerText = "Dog was Added! ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Enterageage'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class EnterageageParams
    {
        
        #region Fields
        /// <summary>
        /// Type '4' in 'DogAge' text box
        /// </summary>
        public string UIDogAgeEditText = "4";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EnterDogAgedogage'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class EnterDogAgedogageParams
    {
        
        #region Fields
        /// <summary>
        /// Type '3' in 'DogAge' text box
        /// </summary>
        public string UIDogAgeEditText = "3";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EnterDogNamedogname'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class EnterDogNamedognameParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Hootch' in 'DogName' text box
        /// </summary>
        public string UIDogNameEditText = "Hootch";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'EnterDogWeightdogweight'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class EnterDogWeightdogweightParams
    {
        
        #region Fields
        /// <summary>
        /// Type '11' in 'DogWeight' text box
        /// </summary>
        public string UIDogWeightEditText = "11";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Enterweightweight'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class EnterweightweightParams
    {
        
        #region Fields
        /// <summary>
        /// Type '11' in 'DogWeight' text box
        /// </summary>
        public string UIDogWeightEditText = "11";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'NavigatetoAddnewdog'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class NavigatetoAddnewdogParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://drookddc.azurewebsites.net/' using new browser instance
        /// </summary>
        public string UINewtabInternetExplorWindowUrl = "http://drookddc.azurewebsites.net/";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Navigatetopage'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class NavigatetopageParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://drookddc.azurewebsites.net/' using new browser instance
        /// </summary>
        public string UINewtabInternetExplorWindowUrl = "http://drookddc.azurewebsites.net/";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINewtabInternetExplorWindow : BrowserWindow
    {
        
        public UINewtabInternetExplorWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "New tab";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("New tab");
            this.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIFavoritesBarToolBar UIFavoritesBarToolBar
        {
            get
            {
                if ((this.mUIFavoritesBarToolBar == null))
                {
                    this.mUIFavoritesBarToolBar = new UIFavoritesBarToolBar(this);
                }
                return this.mUIFavoritesBarToolBar;
            }
        }
        
        public UIManageDogDogDaycareTDocument UIManageDogDogDaycareTDocument
        {
            get
            {
                if ((this.mUIManageDogDogDaycareTDocument == null))
                {
                    this.mUIManageDogDogDaycareTDocument = new UIManageDogDogDaycareTDocument(this);
                }
                return this.mUIManageDogDogDaycareTDocument;
            }
        }
        
        public UIAddressBarClient UIAddressBarClient
        {
            get
            {
                if ((this.mUIAddressBarClient == null))
                {
                    this.mUIAddressBarClient = new UIAddressBarClient(this);
                }
                return this.mUIAddressBarClient;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIAddressComboControlToolBar UIAddressComboControlToolBar
        {
            get
            {
                if ((this.mUIAddressComboControlToolBar == null))
                {
                    this.mUIAddressComboControlToolBar = new UIAddressComboControlToolBar(this);
                }
                return this.mUIAddressComboControlToolBar;
            }
        }
        
        public UIManageDogDogDaycareTDocument1 UIManageDogDogDaycareTDocument1
        {
            get
            {
                if ((this.mUIManageDogDogDaycareTDocument1 == null))
                {
                    this.mUIManageDogDogDaycareTDocument1 = new UIManageDogDogDaycareTDocument1(this);
                }
                return this.mUIManageDogDogDaycareTDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIFavoritesBarToolBar mUIFavoritesBarToolBar;
        
        private UIManageDogDogDaycareTDocument mUIManageDogDogDaycareTDocument;
        
        private UIAddressBarClient mUIAddressBarClient;
        
        private UIItemWindow mUIItemWindow;
        
        private UIAddressComboControlToolBar mUIAddressComboControlToolBar;
        
        private UIManageDogDogDaycareTDocument1 mUIManageDogDogDaycareTDocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIFavoritesBarToolBar : WinToolBar
    {
        
        public UIFavoritesBarToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Favorites Bar";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinButton UIDDCButton
        {
            get
            {
                if ((this.mUIDDCButton == null))
                {
                    this.mUIDDCButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIDDCButton.SearchProperties[WinButton.PropertyNames.Name] = "DDC";
                    this.mUIDDCButton.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUIDDCButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIDDCButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIManageDogDogDaycareTDocument : HtmlDocument
    {
        
        public UIManageDogDogDaycareTDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Manage Dog - Dog Daycare Tracker";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://drookddc.azurewebsites.net/";
            this.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIDogNameEdit
        {
            get
            {
                if ((this.mUIDogNameEdit == null))
                {
                    this.mUIDogNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDogNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "DogName";
                    this.mUIDogNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "DogName";
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "DogName";
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"DogName\" class=\"form-control\" id=\"";
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIDogNameEdit.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIDogNameEdit;
            }
        }
        
        public HtmlEdit UIDogWeightEdit
        {
            get
            {
                if ((this.mUIDogWeightEdit == null))
                {
                    this.mUIDogWeightEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDogWeightEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "DogWeight";
                    this.mUIDogWeightEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "DogWeight";
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "DogWeight";
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"DogWeight\" class=\"form-control\" id";
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIDogWeightEdit.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIDogWeightEdit;
            }
        }
        
        public HtmlEdit UIDogAgeEdit
        {
            get
            {
                if ((this.mUIDogAgeEdit == null))
                {
                    this.mUIDogAgeEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDogAgeEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "DogAge";
                    this.mUIDogAgeEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "DogAge";
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "DogAge";
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"DogAge\" class=\"form-control\" id=\"D";
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIDogAgeEdit.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIDogAgeEdit;
            }
        }
        
        public HtmlInputButton UIAddDogButton
        {
            get
            {
                if ((this.mUIAddDogButton == null))
                {
                    this.mUIAddDogButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIAddDogButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIAddDogButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIAddDogButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Add Dog";
                    this.mUIAddDogButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIAddDogButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIAddDogButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIAddDogButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" type=\"submit\" va";
                    this.mUIAddDogButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "4";
                    this.mUIAddDogButton.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIAddDogButton;
            }
        }
        
        public HtmlDiv UIDogwasAddedPane
        {
            get
            {
                if ((this.mUIDogwasAddedPane == null))
                {
                    this.mUIDogwasAddedPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIDogwasAddedPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIDogwasAddedPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIDogwasAddedPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Dog was Added! ";
                    this.mUIDogwasAddedPane.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIDogwasAddedPane;
            }
        }
        
        public HtmlDiv UIDogwasAddedPane1
        {
            get
            {
                if ((this.mUIDogwasAddedPane1 == null))
                {
                    this.mUIDogwasAddedPane1 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIDogwasAddedPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIDogwasAddedPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIDogwasAddedPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Dog was Added!";
                    this.mUIDogwasAddedPane1.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIDogwasAddedPane1;
            }
        }
        
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["TagName"] = "FORM";
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.FilterProperties["Class"] = "form-horizontal";
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = "class=\"form-horizontal\" role=\"form\" acti";
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIItemCustom.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public HtmlDiv UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "col-md-10";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"col-md-10\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "11";
                    this.mUIItemPane.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        
        public HtmlDiv UIItemPane1
        {
            get
            {
                if ((this.mUIItemPane1 == null))
                {
                    this.mUIItemPane1 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane1.FilterProperties[HtmlDiv.PropertyNames.Class] = "col-md-10";
                    this.mUIItemPane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"col-md-10\"";
                    this.mUIItemPane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "13";
                    this.mUIItemPane1.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIItemPane1;
            }
        }
        
        public HtmlDiv UIItemPane2
        {
            get
            {
                if ((this.mUIItemPane2 == null))
                {
                    this.mUIItemPane2 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItemPane2.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane2.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane2.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane2.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane2.FilterProperties[HtmlDiv.PropertyNames.Class] = "col-md-offset-2 col-md-10";
                    this.mUIItemPane2.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"col-md-offset-2 col-md-10\"";
                    this.mUIItemPane2.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "15";
                    this.mUIItemPane2.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIItemPane2;
            }
        }
        
        public HtmlDiv UIDogwasAddedPane2
        {
            get
            {
                if ((this.mUIDogwasAddedPane2 == null))
                {
                    this.mUIDogwasAddedPane2 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIDogwasAddedPane2.SearchProperties[HtmlDiv.PropertyNames.Id] = "divForResult";
                    this.mUIDogwasAddedPane2.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIDogwasAddedPane2.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Dog was Added";
                    this.mUIDogwasAddedPane2.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIDogwasAddedPane2.FilterProperties[HtmlDiv.PropertyNames.Class] = "col-md-offset-2 col-md-10";
                    this.mUIDogwasAddedPane2.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"col-md-offset-2 col-md-10\" id=\"divForResult\"";
                    this.mUIDogwasAddedPane2.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "17";
                    this.mUIDogwasAddedPane2.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIDogwasAddedPane2;
            }
        }
        
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        
        public HtmlDiv UIDogwasAddedPane3
        {
            get
            {
                if ((this.mUIDogwasAddedPane3 == null))
                {
                    this.mUIDogwasAddedPane3 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIDogwasAddedPane3.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIDogwasAddedPane3.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIDogwasAddedPane3.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Dog was Added";
                    this.mUIDogwasAddedPane3.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIDogwasAddedPane3.FilterProperties[HtmlDiv.PropertyNames.Class] = "col-md-offset-2 col-md-10";
                    this.mUIDogwasAddedPane3.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"col-md-offset-2 col-md-10\"";
                    this.mUIDogwasAddedPane3.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "17";
                    this.mUIDogwasAddedPane3.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIDogwasAddedPane3;
            }
        }
        
        public HtmlDiv UIDogwasAddedPane4
        {
            get
            {
                if ((this.mUIDogwasAddedPane4 == null))
                {
                    this.mUIDogwasAddedPane4 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIDogwasAddedPane4.SearchProperties[HtmlDiv.PropertyNames.Id] = "divForInnerText";
                    this.mUIDogwasAddedPane4.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIDogwasAddedPane4.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Dog was Added";
                    this.mUIDogwasAddedPane4.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIDogwasAddedPane4.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIDogwasAddedPane4.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"divForInnerText\"";
                    this.mUIDogwasAddedPane4.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "17";
                    this.mUIDogwasAddedPane4.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIDogwasAddedPane4;
            }
        }
        
        public HtmlDiv UIDogwasAddedPane5
        {
            get
            {
                if ((this.mUIDogwasAddedPane5 == null))
                {
                    this.mUIDogwasAddedPane5 = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIDogwasAddedPane5.SearchProperties[HtmlDiv.PropertyNames.Id] = "dogwasaddeddiv2";
                    this.mUIDogwasAddedPane5.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIDogwasAddedPane5.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Dog was Added! ";
                    this.mUIDogwasAddedPane5.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIDogwasAddedPane5.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIDogwasAddedPane5.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"dogwasaddeddiv2\"";
                    this.mUIDogwasAddedPane5.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "15";
                    this.mUIDogwasAddedPane5.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIDogwasAddedPane5;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIDogNameEdit;
        
        private HtmlEdit mUIDogWeightEdit;
        
        private HtmlEdit mUIDogAgeEdit;
        
        private HtmlInputButton mUIAddDogButton;
        
        private HtmlDiv mUIDogwasAddedPane;
        
        private HtmlDiv mUIDogwasAddedPane1;
        
        private HtmlCustom mUIItemCustom;
        
        private HtmlDiv mUIItemPane;
        
        private HtmlDiv mUIItemPane1;
        
        private HtmlDiv mUIItemPane2;
        
        private HtmlDiv mUIDogwasAddedPane2;
        
        private UIItemTable mUIItemTable;
        
        private HtmlDiv mUIDogwasAddedPane3;
        
        private HtmlDiv mUIDogwasAddedPane4;
        
        private HtmlDiv mUIDogwasAddedPane5;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemTable : HtmlTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Dog was Added";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = null;
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "1";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = null;
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
            #endregion
        }
        
        #region Properties
        public HtmlCell UIDogwasAddedCell
        {
            get
            {
                if ((this.mUIDogwasAddedCell == null))
                {
                    this.mUIDogwasAddedCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIDogwasAddedCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIDogwasAddedCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIDogwasAddedCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "8";
                    this.mUIDogwasAddedCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUIDogwasAddedCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUIDogwasAddedCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIDogwasAddedCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIDogwasAddedCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "1";
                    this.mUIDogwasAddedCell.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIDogwasAddedCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCell mUIDogwasAddedCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAddressBarClient : WinClient
    {
        
        public UIAddressBarClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Address Bar";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchusinEdit
        {
            get
            {
                if ((this.mUIAddressandsearchusinEdit == null))
                {
                    this.mUIAddressandsearchusinEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchusinEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search using Bing";
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUIAddressandsearchusinEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchusinEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Address and search using Bing";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Edit";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAddressComboControlToolBar : WinToolBar
    {
        
        public UIAddressComboControlToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Address Combo Control";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIItemMenuItem
        {
            get
            {
                if ((this.mUIItemMenuItem == null))
                {
                    this.mUIItemMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIItemMenuItem.SearchProperties[WinMenuItem.PropertyNames.Instance] = "2";
                    this.mUIItemMenuItem.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUIItemMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIItemMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIManageDogDogDaycareTDocument1 : HtmlDocument
    {
        
        public UIManageDogDogDaycareTDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Manage Dog - Dog Daycare Tracker";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/dogmanager/index";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://drookddc.azurewebsites.net/dogmanager/index";
            this.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIDogNameEdit
        {
            get
            {
                if ((this.mUIDogNameEdit == null))
                {
                    this.mUIDogNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDogNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "DogName";
                    this.mUIDogNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "DogName";
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "DogName";
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"DogName\" class=\"form-control\" id=\"";
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIDogNameEdit.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIDogNameEdit;
            }
        }
        
        public HtmlEdit UIDogWeightEdit
        {
            get
            {
                if ((this.mUIDogWeightEdit == null))
                {
                    this.mUIDogWeightEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDogWeightEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "DogWeight";
                    this.mUIDogWeightEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "DogWeight";
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "DogWeight";
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"DogWeight\" class=\"form-control\" id";
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIDogWeightEdit.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIDogWeightEdit;
            }
        }
        
        public HtmlEdit UIDogAgeEdit
        {
            get
            {
                if ((this.mUIDogAgeEdit == null))
                {
                    this.mUIDogAgeEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDogAgeEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "DogAge";
                    this.mUIDogAgeEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "DogAge";
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "DogAge";
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"DogAge\" class=\"form-control\" id=\"D";
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIDogAgeEdit.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIDogAgeEdit;
            }
        }
        
        public HtmlInputButton UIAddDogButton
        {
            get
            {
                if ((this.mUIAddDogButton == null))
                {
                    this.mUIAddDogButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIAddDogButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIAddDogButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIAddDogButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Add Dog";
                    this.mUIAddDogButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIAddDogButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIAddDogButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIAddDogButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" type=\"submit\" va";
                    this.mUIAddDogButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "4";
                    this.mUIAddDogButton.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIAddDogButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIDogNameEdit;
        
        private HtmlEdit mUIDogWeightEdit;
        
        private HtmlEdit mUIDogAgeEdit;
        
        private HtmlInputButton mUIAddDogButton;
        #endregion
    }
}
