// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace DDC.CUI1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// DrookUI
        /// </summary>
        public void DrookUI()
        {

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.

            // To test Windows Store apps, use the Coded UI Test project template for Windows Store apps under the Windows Store node.
        }
        
        /// <summary>
        /// Enterdogage - Test Case 56 - Use 'EnterdogageParams' to pass parameters into this method.
        /// </summary>
        public void Enterdogage()
        {
            #region Variable Declarations
            WinTabList uITabRowTabList = this.UINewtabInternetExplorWindow.UIItemWindow.UINavigationBarClient.UITabRowTabList;
            WinEdit uIAddressandsearchusinEdit = this.UINewtabInternetExplorWindow.UIAddressBarClient.UIAddressandsearchusinEdit;
            WinEdit uIItemEdit = this.UINewtabInternetExplorWindow.UIItemWindow1.UIItemEdit;
            HtmlEdit uIDogNameEdit = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIDogNameEdit;
            HtmlEdit uIDogWeightEdit = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIDogWeightEdit;
            HtmlEdit uIDogAgeEdit = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIDogAgeEdit;
            HtmlInputButton uIAddDogButton = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIAddDogButton;
            #endregion

            // Go to web page 'about:Tabs' using new browser instance
            this.UINewtabInternetExplorWindow.LaunchUrl(new System.Uri(this.EnterdogageParams.UINewtabInternetExplorWindowUrl));

            // Click 'Tab Row' tab list
            Mouse.Click(uITabRowTabList, new Point(300, 3));

            // Click 'Address and search using Bing' text box
            Mouse.Click(uIAddressandsearchusinEdit, new Point(131, 9));

            // Type 'Control + v' in text box
            Keyboard.SendKeys(uIItemEdit, this.EnterdogageParams.UIItemEditSendKeys, ModifierKeys.Control);

            // Type '{Enter}' in text box
            Keyboard.SendKeys(uIItemEdit, this.EnterdogageParams.UIItemEditSendKeys1, ModifierKeys.None);

            // Type 'steve' in 'DogName' text box
            uIDogNameEdit.Text = this.EnterdogageParams.UIDogNameEditText;

            // Type '{Tab}' in 'DogName' text box
            Keyboard.SendKeys(uIDogNameEdit, this.EnterdogageParams.UIDogNameEditSendKeys, ModifierKeys.None);

            // Type '20' in 'DogWeight' text box
            uIDogWeightEdit.Text = this.EnterdogageParams.UIDogWeightEditText;

            // Type '{Tab}' in 'DogWeight' text box
            Keyboard.SendKeys(uIDogWeightEdit, this.EnterdogageParams.UIDogWeightEditSendKeys, ModifierKeys.None);

            // Type '96' in 'DogAge' text box
            uIDogAgeEdit.Text = this.EnterdogageParams.UIDogAgeEditText;

            // Click 'Add Dog' button
            Mouse.Click(uIAddDogButton, new Point(34, 24));
        }
        
        /// <summary>
        /// AddDogNoErrors - Use 'AddDogNoErrorsParams' to pass parameters into this method.
        /// </summary>
        public void AddDogNoErrors()
        {
            #region Variable Declarations
            BrowserWindow uINewtabInternetExplorWindow = this.UINewtabInternetExplorWindow;
            HtmlEdit uIDogNameEdit = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIDogNameEdit;
            HtmlEdit uIDogWeightEdit = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIDogWeightEdit;
            HtmlEdit uIDogAgeEdit = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIDogAgeEdit;
            HtmlInputButton uIAddDogButton = this.UINewtabInternetExplorWindow.UIManageDogDogDaycareTDocument.UIAddDogButton;
            #endregion

            // Go to web page 'http://drookddc.azurewebsites.net/'
            uINewtabInternetExplorWindow.NavigateToUrl(new System.Uri(this.AddDogNoErrorsParams.UINewtabInternetExplorWindowUrl));

            // Type 'buxton' in 'DogName' text box
            uIDogNameEdit.Text = this.AddDogNoErrorsParams.UIDogNameEditText;

            // Type '{Tab}' in 'DogName' text box
            Keyboard.SendKeys(uIDogNameEdit, this.AddDogNoErrorsParams.UIDogNameEditSendKeys, ModifierKeys.None);

            // Type '60' in 'DogWeight' text box
            uIDogWeightEdit.Text = this.AddDogNoErrorsParams.UIDogWeightEditText;

            // Type '{Tab}' in 'DogWeight' text box
            Keyboard.SendKeys(uIDogWeightEdit, this.AddDogNoErrorsParams.UIDogWeightEditSendKeys, ModifierKeys.None);

            // Type '2' in 'DogAge' text box
            uIDogAgeEdit.Text = this.AddDogNoErrorsParams.UIDogAgeEditText;

            // Click 'Add Dog' button
            Mouse.Click(uIAddDogButton, new Point(35, 10));
        }
        
        #region Properties
        public virtual EnterdogageParams EnterdogageParams
        {
            get
            {
                if ((this.mEnterdogageParams == null))
                {
                    this.mEnterdogageParams = new EnterdogageParams();
                }
                return this.mEnterdogageParams;
            }
        }
        
        public virtual AddDogNoErrorsParams AddDogNoErrorsParams
        {
            get
            {
                if ((this.mAddDogNoErrorsParams == null))
                {
                    this.mAddDogNoErrorsParams = new AddDogNoErrorsParams();
                }
                return this.mAddDogNoErrorsParams;
            }
        }
        
        public UINewtabInternetExplorWindow UINewtabInternetExplorWindow
        {
            get
            {
                if ((this.mUINewtabInternetExplorWindow == null))
                {
                    this.mUINewtabInternetExplorWindow = new UINewtabInternetExplorWindow();
                }
                return this.mUINewtabInternetExplorWindow;
            }
        }
        #endregion
        
        #region Fields
        private EnterdogageParams mEnterdogageParams;
        
        private AddDogNoErrorsParams mAddDogNoErrorsParams;
        
        private UINewtabInternetExplorWindow mUINewtabInternetExplorWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Enterdogage'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class EnterdogageParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'about:Tabs' using new browser instance
        /// </summary>
        public string UINewtabInternetExplorWindowUrl = "about:Tabs";
        
        /// <summary>
        /// Type 'Control + v' in text box
        /// </summary>
        public string UIItemEditSendKeys = "v";
        
        /// <summary>
        /// Type '{Enter}' in text box
        /// </summary>
        public string UIItemEditSendKeys1 = "{Enter}";
        
        /// <summary>
        /// Type 'steve' in 'DogName' text box
        /// </summary>
        public string UIDogNameEditText = "steve";
        
        /// <summary>
        /// Type '{Tab}' in 'DogName' text box
        /// </summary>
        public string UIDogNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '20' in 'DogWeight' text box
        /// </summary>
        public string UIDogWeightEditText = "20";
        
        /// <summary>
        /// Type '{Tab}' in 'DogWeight' text box
        /// </summary>
        public string UIDogWeightEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '96' in 'DogAge' text box
        /// </summary>
        public string UIDogAgeEditText = "96";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AddDogNoErrors'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class AddDogNoErrorsParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://drookddc.azurewebsites.net/'
        /// </summary>
        public string UINewtabInternetExplorWindowUrl = "http://drookddc.azurewebsites.net/";
        
        /// <summary>
        /// Type 'buxton' in 'DogName' text box
        /// </summary>
        public string UIDogNameEditText = "buxton";
        
        /// <summary>
        /// Type '{Tab}' in 'DogName' text box
        /// </summary>
        public string UIDogNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '60' in 'DogWeight' text box
        /// </summary>
        public string UIDogWeightEditText = "60";
        
        /// <summary>
        /// Type '{Tab}' in 'DogWeight' text box
        /// </summary>
        public string UIDogWeightEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '2' in 'DogAge' text box
        /// </summary>
        public string UIDogAgeEditText = "2";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINewtabInternetExplorWindow : BrowserWindow
    {
        
        public UINewtabInternetExplorWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "New tab";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("New tab");
            this.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIAddressBarClient UIAddressBarClient
        {
            get
            {
                if ((this.mUIAddressBarClient == null))
                {
                    this.mUIAddressBarClient = new UIAddressBarClient(this);
                }
                return this.mUIAddressBarClient;
            }
        }
        
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIManageDogDogDaycareTDocument UIManageDogDogDaycareTDocument
        {
            get
            {
                if ((this.mUIManageDogDogDaycareTDocument == null))
                {
                    this.mUIManageDogDogDaycareTDocument = new UIManageDogDogDaycareTDocument(this);
                }
                return this.mUIManageDogDogDaycareTDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UIAddressBarClient mUIAddressBarClient;
        
        private UIItemWindow1 mUIItemWindow1;
        
        private UIManageDogDogDaycareTDocument mUIManageDogDogDaycareTDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public UINavigationBarClient UINavigationBarClient
        {
            get
            {
                if ((this.mUINavigationBarClient == null))
                {
                    this.mUINavigationBarClient = new UINavigationBarClient(this);
                }
                return this.mUINavigationBarClient;
            }
        }
        #endregion
        
        #region Fields
        private UINavigationBarClient mUINavigationBarClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UINavigationBarClient : WinClient
    {
        
        public UINavigationBarClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinTabList UITabRowTabList
        {
            get
            {
                if ((this.mUITabRowTabList == null))
                {
                    this.mUITabRowTabList = new WinTabList(this);
                    #region Search Criteria
                    this.mUITabRowTabList.SearchProperties[WinTabList.PropertyNames.Name] = "Tab Row";
                    this.mUITabRowTabList.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUITabRowTabList;
            }
        }
        #endregion
        
        #region Fields
        private WinTabList mUITabRowTabList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIAddressBarClient : WinClient
    {
        
        public UIAddressBarClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Address Bar";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchusinEdit
        {
            get
            {
                if ((this.mUIAddressandsearchusinEdit == null))
                {
                    this.mUIAddressandsearchusinEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchusinEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search using Bing";
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUIAddressandsearchusinEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchusinEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Address and search using Bing";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Edit";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIManageDogDogDaycareTDocument : HtmlDocument
    {
        
        public UIManageDogDogDaycareTDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Manage Dog - Dog Daycare Tracker";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://drookddc.azurewebsites.net/";
            this.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIDogNameEdit
        {
            get
            {
                if ((this.mUIDogNameEdit == null))
                {
                    this.mUIDogNameEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDogNameEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "DogName";
                    this.mUIDogNameEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "DogName";
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "DogName";
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"DogName\" class=\"form-control\" id=\"";
                    this.mUIDogNameEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIDogNameEdit.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIDogNameEdit;
            }
        }
        
        public HtmlEdit UIDogWeightEdit
        {
            get
            {
                if ((this.mUIDogWeightEdit == null))
                {
                    this.mUIDogWeightEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDogWeightEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "DogWeight";
                    this.mUIDogWeightEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "DogWeight";
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "DogWeight";
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"DogWeight\" class=\"form-control\" id";
                    this.mUIDogWeightEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIDogWeightEdit.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIDogWeightEdit;
            }
        }
        
        public HtmlEdit UIDogAgeEdit
        {
            get
            {
                if ((this.mUIDogAgeEdit == null))
                {
                    this.mUIDogAgeEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIDogAgeEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "DogAge";
                    this.mUIDogAgeEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "DogAge";
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "DogAge";
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"DogAge\" class=\"form-control\" id=\"D";
                    this.mUIDogAgeEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIDogAgeEdit.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIDogAgeEdit;
            }
        }
        
        public HtmlInputButton UIAddDogButton
        {
            get
            {
                if ((this.mUIAddDogButton == null))
                {
                    this.mUIAddDogButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIAddDogButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIAddDogButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIAddDogButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Add Dog";
                    this.mUIAddDogButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIAddDogButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIAddDogButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-default";
                    this.mUIAddDogButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-default\" type=\"submit\" va";
                    this.mUIAddDogButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "4";
                    this.mUIAddDogButton.WindowTitles.Add("Manage Dog - Dog Daycare Tracker");
                    #endregion
                }
                return this.mUIAddDogButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIDogNameEdit;
        
        private HtmlEdit mUIDogWeightEdit;
        
        private HtmlEdit mUIDogAgeEdit;
        
        private HtmlInputButton mUIAddDogButton;
        #endregion
    }
}
